#index:
#    path: /
#    controller: App\Controller\DefaultController::index

newIntervenant_success:
  path:         /newintervenantsuccess
  controller:	Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: '/static/intervenant_success.html.twig'
    maxAge: 86400
    sharedAge: 86400